//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marccello
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.MajorCourses = new HashSet<MajorCourse>();
        }
    
        public int course_id { get; set; }
        public string name { get; set; }
        public string course_number { get; set; }
    
        public virtual ICollection<MajorCourse> MajorCourses { get; set; }
    }
}
