//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marccello
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.semesters = new HashSet<semester>();
        }
    
        public string course_id { get; set; }
        public string department { get; set; }
        public string course_name { get; set; }
        public string depart_name { get; set; }
    
        public virtual major major { get; set; }
        public virtual ICollection<semester> semesters { get; set; }
    }
}
