//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marccello
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        public Major()
        {
            this.Cours = new HashSet<Cours>();
        }
    
        public string name { get; set; }
        public string department { get; set; }
    
        public virtual ICollection<Cours> Cours { get; set; }
    }
}
