<?xml version="1.0" encoding="utf-8"?><Database Name="marccello" Class="majorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=USER-1-PC;Initial Catalog=marccello;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="marccelloConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.major" Member="majors">
    <Type Name="major">
      <Column Name="department" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>